"use client";

import {
  AlertTriangle,
  AlertCircle,
  ShieldAlert,
  Activity,
} from "lucide-react";

import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";

interface Props {
  risk: string;
  matchedCases: number;
}

export default function RiskSummary({
  risk,
  matchedCases,
}: Props) {
  const getRiskConfig = () => {
    switch (risk.toUpperCase()) {
      case "HIGH":
        return {
          icon: <ShieldAlert className="h-8 w-8 text-red-500" />,
          badgeClass:
            "bg-red-500/20 text-red-400 border-red-500/30",
          title: "High Risk",
          valueColor: "text-red-400",
        };

      case "MEDIUM":
        return {
          icon: <AlertTriangle className="h-8 w-8 text-yellow-400" />,
          badgeClass:
            "bg-yellow-500/20 text-yellow-400 border-yellow-500/30",
          title: "Medium Risk",
          valueColor: "text-yellow-400",
        };

      default:
        return {
          icon: <AlertCircle className="h-8 w-8 text-green-500" />,
          badgeClass:
            "bg-green-500/20 text-green-400 border-green-500/30",
          title: "Low Risk",
          valueColor: "text-green-400",
        };
    }
  };

  const config = getRiskConfig();

  return (
    <Card className="border-white/10 bg-zinc-900 p-6">

      <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">

        <div className="flex items-center gap-4">

          {config.icon}

          <div>

            <h2 className="text-2xl font-semibold text-white">
              AI Risk Assessment
            </h2>

            <p className="text-sm text-zinc-400">
              Historical intelligence generated by the Lessons Learned Engine.
            </p>

          </div>

        </div>

        <Badge className={config.badgeClass}>
          {config.title}
        </Badge>

      </div>

      <div className="mt-6 grid grid-cols-1 gap-4 md:grid-cols-3">

        <div className="rounded-xl border border-white/10 bg-zinc-800 p-5">

          <p className="text-sm text-zinc-400">
            Historical Matches
          </p>

          <h3 className="mt-2 text-3xl font-bold text-white">
            {matchedCases}
          </h3>

        </div>

        <div className="rounded-xl border border-white/10 bg-zinc-800 p-5">

          <p className="text-sm text-zinc-400">
            Current Risk
          </p>

          <h3 className={`mt-2 text-3xl font-bold ${config.valueColor}`}>
            {risk}
          </h3>

        </div>

        <div className="rounded-xl border border-white/10 bg-zinc-800 p-5">

          <div className="flex items-center gap-2">

            <Activity className="h-5 w-5 text-emerald-400" />

            <p className="text-sm text-zinc-400">
              Engine Status
            </p>

          </div>

          <h3 className="mt-2 text-3xl font-bold text-emerald-400">
            ACTIVE
          </h3>

        </div>

      </div>

    </Card>
  );
}